/*
 * PokeRogue Mini - a small desktop wrapper around the official pokerogue.net
 *
 * A slim toolbar sits at the top of the window (tone / brightness / opacity /
 * reload / mute / size preset / always-on-top / hide); the game renders in a
 * WebContentsView below it. A tray icon (pokeball) lives next to the clock.
 *
 * Hotkeys (while the window is focused):
 *   Ctrl+G      toggle tone on/off (remembers the last tone & intensity)
 *   Ctrl+M      toggle mute
 *   Ctrl+P      toggle size preset (mini bottom-right / normal centered)
 *   Ctrl+T      toggle always-on-top
 *   Ctrl+Down/Up     dim / brighten the screen
 *   Ctrl+Left/Right  more / less transparent
 *   Ctrl+R      reload the game page
 * Global (works even when hidden):
 *   Ctrl+Alt+P  boss key - hide/show the window
 *
 * Audio: muted by default; even when unmuted, audio auto-mutes while the
 * window is not focused or hidden.
 */
const {
  app,
  BrowserWindow,
  Menu,
  Tray,
  WebContentsView,
  globalShortcut,
  ipcMain,
  nativeImage,
  screen,
  session,
  shell,
} = require("electron");
const fs = require("fs");
const path = require("path");
const browser = require("./browser");

const HOME_URL = "https://pokerogue.net/";
// Present as a plain Chrome browser so Google/Discord OAuth login pages don't
// reject the embedded window.
const CHROME_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";
const DEFAULT_TOOLBAR_HEIGHT = 26;
let toolbarHeight = DEFAULT_TOOLBAR_HEIGHT;
const BRIGHTNESS_MIN = 20;
const OPACITY_MIN = 30;
const STEP = 5;
const TONES = ["none", "gray", "sepia"];
const PRESET_MINI = { width: 448, height: 252 + DEFAULT_TOOLBAR_HEIGHT };
const PRESET_NORMAL = { width: 854, height: 480 + DEFAULT_TOOLBAR_HEIGHT };
// 16x16 pokeball, generated by scripts/gen-icon.js
const TRAY_ICON =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAY0lEQVR42mNgoDaQk5P7jw8TpfmejQ1WjNcQQprxGkKsZpyG4NKMz2CCBoDEPnz4AMa45IkOeYIxQhUDvn79ioLRvYBNHq8BMEX45DC8gE0hPoOxpgWyNBNrCEn5gazMRA4AAIIghN4gagnbAAAAAElFTkSuQmCC";

const settingsPath = () => path.join(app.getPath("userData"), "settings.json");

// toneAmount/brightness/opacity are percentages
let settings = {
  bounds: { width: PRESET_NORMAL.width, height: PRESET_NORMAL.height },
  tone: "gray",
  toneAmount: 100,
  lastTone: "gray",
  brightness: 100,
  opacity: 100,
  muted: true,
  alwaysOnTop: false,
  claudeApiKey: "",
  browserBounds: null,
};

function loadSettings() {
  let stored = {};
  try {
    stored = JSON.parse(fs.readFileSync(settingsPath(), "utf8"));
  } catch {
    /* first run */
  }
  // Migrate from the old grayscale-slider format
  if (typeof stored.grayscale === "number" && stored.tone === undefined) {
    stored.tone = stored.grayscale > 0 ? "gray" : "none";
    stored.toneAmount = stored.grayscale > 0 ? stored.grayscale : stored.lastGrayscale || 100;
  }
  delete stored.grayscale;
  delete stored.lastGrayscale;
  settings = { ...settings, ...stored };
  if (!TONES.includes(settings.tone)) {
    settings.tone = "none";
  }
  if (!TONES.includes(settings.lastTone) || settings.lastTone === "none") {
    settings.lastTone = "gray";
  }
  settings.toneAmount = Math.min(Math.max(settings.toneAmount, 0), 100);
  settings.brightness = Math.min(Math.max(settings.brightness, BRIGHTNESS_MIN), 100);
  settings.opacity = Math.min(Math.max(settings.opacity || 100, OPACITY_MIN), 100);
  settings.muted = settings.muted !== false;
}

function saveSettings() {
  try {
    fs.writeFileSync(settingsPath(), JSON.stringify(settings, null, 2));
  } catch {
    /* not fatal */
  }
}

let win = null;
let gameView = null;
let tray = null;
let hiddenByBossKey = false;
let windowFocused = true;

function pushState() {
  if (win && !win.webContents.isDestroyed()) {
    win.webContents.send("state", settings);
  }
}

function updateMute() {
  if (gameView) {
    gameView.webContents.setAudioMuted(settings.muted || !windowFocused || hiddenByBossKey);
  }
}

function applyFilters() {
  if (!gameView) {
    return;
  }
  const filters = [];
  if (settings.tone === "gray" && settings.toneAmount > 0) {
    filters.push(`grayscale(${settings.toneAmount / 100})`);
  } else if (settings.tone === "sepia" && settings.toneAmount > 0) {
    filters.push(`sepia(${settings.toneAmount / 100})`);
  }
  if (settings.brightness < 100) {
    filters.push(`brightness(${settings.brightness / 100})`);
  }
  const filter = filters.join(" ");
  gameView.webContents
    .executeJavaScript(`document.documentElement.style.filter = ${JSON.stringify(filter)}; undefined;`)
    .catch(() => {
      /* page not ready yet; dom-ready will re-apply */
    });
  const toneTag =
    settings.tone !== "none" && settings.toneAmount > 0
      ? ` [${settings.tone === "gray" ? "BW" : "SP"} ${settings.toneAmount}%]`
      : "";
  const tags = [
    toneTag,
    settings.brightness < 100 ? ` [${settings.brightness}%]` : "",
    settings.muted ? " [🔇]" : "",
    settings.alwaysOnTop ? " [TOP]" : "",
  ].join("");
  if (win) {
    win.setTitle(`PokeRogue Mini${tags}`);
  }
  pushState();
}

function updateSettings(patch) {
  Object.assign(settings, patch);
  settings.toneAmount = Math.min(Math.max(settings.toneAmount, 0), 100);
  settings.brightness = Math.min(Math.max(settings.brightness, BRIGHTNESS_MIN), 100);
  settings.opacity = Math.min(Math.max(settings.opacity, OPACITY_MIN), 100);
  if (settings.tone !== "none") {
    settings.lastTone = settings.tone;
  }
  if ("alwaysOnTop" in patch && win) {
    win.setAlwaysOnTop(settings.alwaysOnTop);
  }
  if ("opacity" in patch && win) {
    win.setOpacity(settings.opacity / 100);
  }
  if ("muted" in patch) {
    updateMute();
  }
  saveSettings();
  applyFilters();
}

function togglePreset() {
  if (!win) {
    return;
  }
  const bounds = win.getBounds();
  const workArea = screen.getDisplayMatching(bounds).workArea;
  const isMini = bounds.width <= PRESET_MINI.width + 40;
  if (isMini) {
    win.setBounds({
      width: PRESET_NORMAL.width,
      height: PRESET_NORMAL.height,
      x: workArea.x + Math.round((workArea.width - PRESET_NORMAL.width) / 2),
      y: workArea.y + Math.round((workArea.height - PRESET_NORMAL.height) / 2),
    });
  } else {
    win.setBounds({
      width: PRESET_MINI.width,
      height: PRESET_MINI.height,
      x: workArea.x + workArea.width - PRESET_MINI.width - 12,
      y: workArea.y + workArea.height - PRESET_MINI.height - 12,
    });
  }
  settings.bounds = win.getBounds();
  saveSettings();
}

function toggleBossKey() {
  if (!win) {
    return;
  }
  if (win.isVisible() && !win.isMinimized()) {
    hiddenByBossKey = true;
    updateMute();
    win.hide();
  } else {
    hiddenByBossKey = false;
    win.show();
    win.focus();
    updateMute();
  }
}

function attachHotkeys(wc) {
  wc.on("before-input-event", (event, input) => {
    if (input.type !== "keyDown" || !input.control || input.alt || input.meta || input.isAutoRepeat) {
      return;
    }
    const key = input.key.toLowerCase();
    if (key === "g") {
      updateSettings({ tone: settings.tone !== "none" ? "none" : settings.lastTone });
    } else if (key === "m") {
      updateSettings({ muted: !settings.muted });
    } else if (key === "p") {
      togglePreset();
    } else if (key === "t") {
      updateSettings({ alwaysOnTop: !settings.alwaysOnTop });
    } else if (key === "arrowdown") {
      updateSettings({ brightness: settings.brightness - STEP });
    } else if (key === "arrowup") {
      updateSettings({ brightness: settings.brightness + STEP });
    } else if (key === "arrowleft") {
      updateSettings({ opacity: settings.opacity - STEP });
    } else if (key === "arrowright") {
      updateSettings({ opacity: settings.opacity + STEP });
    } else if (key === "r") {
      gameView.webContents.reload();
    } else if (key === "l") {
      browser.open(null, true);
    } else {
      return;
    }
    event.preventDefault();
  });
}

function layoutGameView() {
  if (!win || !gameView) {
    return;
  }
  const [width, height] = win.getContentSize();
  gameView.setBounds({ x: 0, y: toolbarHeight, width, height: Math.max(0, height - toolbarHeight) });
}

function createWindow() {
  const ses = session.fromPartition("persist:pokerogue");
  ses.setUserAgent(CHROME_UA);

  win = new BrowserWindow({
    width: settings.bounds.width,
    height: settings.bounds.height,
    x: settings.bounds.x,
    y: settings.bounds.y,
    backgroundColor: "#1b1b1f",
    alwaysOnTop: settings.alwaysOnTop,
    title: "PokeRogue Mini",
    // no native caption text; the toolbar doubles as the (dark) title bar
    titleBarStyle: "hidden",
    titleBarOverlay: { color: "#141416", symbolColor: "#7c7c82", height: 30 },
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  win.setMenu(null);
  if (settings.opacity < 100) {
    win.setOpacity(settings.opacity / 100);
  }
  win.loadFile("toolbar.html");
  win.webContents.on("dom-ready", pushState);

  gameView = new WebContentsView({
    webPreferences: {
      partition: "persist:pokerogue",
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  win.contentView.addChildView(gameView);
  layoutGameView();
  win.on("resize", layoutGameView);

  // Open external links (wiki, discord, oauth popups...) in the default browser.
  gameView.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: "deny" };
  });

  // The inline style is per-document; re-apply after every navigation.
  gameView.webContents.on("dom-ready", applyFilters);

  attachHotkeys(gameView.webContents);
  attachHotkeys(win.webContents);

  // Auto-mute while the window is not focused.
  win.on("blur", () => {
    windowFocused = false;
    updateMute();
  });
  win.on("focus", () => {
    windowFocused = true;
    updateMute();
    // keyboard input should go to the game by default
    gameView.webContents.focus();
  });

  const rememberBounds = () => {
    if (win && !win.isMinimized() && win.isVisible()) {
      settings.bounds = win.getBounds();
    }
  };
  win.on("resized", rememberBounds);
  win.on("moved", rememberBounds);
  win.on("close", () => {
    rememberBounds();
    saveSettings();
  });

  updateMute();
  gameView.webContents.loadURL(HOME_URL);
}

function createTray() {
  tray = new Tray(nativeImage.createFromDataURL(TRAY_ICON));
  tray.setToolTip("PokeRogue Mini — 클릭: 보이기/숨기기");
  tray.on("click", toggleBossKey);
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: "보이기/숨기기 (Ctrl+Alt+P)", click: toggleBossKey },
      { type: "separator" },
      { label: "종료", click: () => app.quit() },
    ]),
  );
}

// Isolated profile for development/testing so a running instance isn't disturbed.
if (process.argv.includes("--test-profile")) {
  app.setPath("userData", path.join(app.getPath("temp"), "pokerogue-mini-test-profile"));
}

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  console.error("another instance is already running; exiting");
  app.quit();
} else {
  process.on("uncaughtException", err => {
    console.error("uncaught exception:", err);
  });

  app.on("second-instance", () => {
    if (win) {
      if (hiddenByBossKey) {
        toggleBossKey();
      }
      if (win.isMinimized()) {
        win.restore();
      }
      win.focus();
    }
  });

  ipcMain.on("set", (_e, patch) => updateSettings(patch));
  ipcMain.on("reload", () => gameView && gameView.webContents.reload());
  ipcMain.on("boss", toggleBossKey);
  ipcMain.on("preset", togglePreset);
  ipcMain.on("focus-game", () => gameView && gameView.webContents.focus());
  ipcMain.on("open-browser", (_e, url, focusAddress) => browser.open(url, focusAddress));
  ipcMain.on("toolbar-height", (_e, h) => {
    const clamped = Math.min(Math.max(Math.round(h), 20), 120);
    if (clamped !== toolbarHeight) {
      toolbarHeight = clamped;
      layoutGameView();
    }
  });

  app.whenReady().then(() => {
    loadSettings();
    browser.init({ settings, save: saveSettings });
    createWindow();
    createTray();
    globalShortcut.register("Control+Alt+P", toggleBossKey);
  });

  app.on("will-quit", () => {
    globalShortcut.unregisterAll();
  });

  app.on("window-all-closed", () => {
    app.quit();
  });
}
