/*
 * PokeRogue Mini - a small desktop wrapper around the official pokerogue.net
 *
 * One window, Chrome-style tabs at the top: the first tab is the game (always
 * running), further tabs are ordinary web pages (wiki, calculators...).
 * A slim monochrome toolbar doubles as the title bar; a Claude strategy panel
 * (with the weekly legendary pickup strip) attaches to the LEFT of the content.
 *
 * Hotkeys (while the window is focused):
 *   Ctrl+G      toggle tone on/off        Ctrl+M      toggle mute
 *   Ctrl+Down/Up     dim / brighten      Ctrl+Left/Right  window opacity
 *   Ctrl+P      size preset              Ctrl+R      reload active tab
 *   Ctrl+T      new web tab              Ctrl+W      close active web tab
 *   Ctrl+Tab    cycle tabs               Ctrl+L      address bar (new tab if on game)
 * Global (works even when hidden):
 *   Ctrl+Alt+P  boss key - hide/show the window
 *
 * Audio: muted by default; even when unmuted, audio auto-mutes while the
 * window is not focused or hidden.
 */
const {
  app,
  BrowserWindow,
  Menu,
  Tray,
  WebContentsView,
  globalShortcut,
  ipcMain,
  nativeImage,
  screen,
  session,
  shell,
} = require("electron");
const fs = require("fs");
const path = require("path");
const chat = require("./chat");
const pickup = require("./pickup");

const HOME_URL = "https://pokerogue.net/";
const WEB_HOME_URL = "https://wiki.pokerogue.net/";
// Present as a plain Chrome browser so Google/Discord OAuth login pages don't
// reject the embedded window.
const CHROME_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";
const DEFAULT_CHROME_HEIGHT = 50;
let chromeHeight = DEFAULT_CHROME_HEIGHT;
const PANEL_W_MIN = 160;
const PANEL_W_MAX = 480;
const PICKUP_RAIL_W = 34; // must match #pickupRail width in toolbar.html
let chatPanelOpen = false;
const BRIGHTNESS_MIN = 20;
const OPACITY_MIN = 30;
const STEP = 5;
const TONES = ["none", "gray", "sepia"];
const PRESET_MINI = { width: 448, height: 252 + DEFAULT_CHROME_HEIGHT };
const PRESET_NORMAL = { width: 854, height: 480 + DEFAULT_CHROME_HEIGHT };
// 16x16 pokeball, generated by scripts/gen-icon.js
const TRAY_ICON =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAY0lEQVR42mNgoDaQk5P7jw8TpfmejQ1WjNcQQprxGkKsZpyG4NKMz2CCBoDEPnz4AMa45IkOeYIxQhUDvn79ioLRvYBNHq8BMEX45DC8gE0hPoOxpgWyNBNrCEn5gazMRA4AAIIghN4gagnbAAAAAElFTkSuQmCC";

const settingsPath = () => path.join(app.getPath("userData"), "settings.json");

// toneAmount/brightness/opacity are percentages
let settings = {
  bounds: { width: PRESET_NORMAL.width, height: PRESET_NORMAL.height },
  tone: "gray",
  toneAmount: 100,
  lastTone: "gray",
  brightness: 100,
  opacity: 100,
  muted: true,
  alwaysOnTop: false,
  claudeApiKey: "",
  chatPanelWidth: 240,
  panelBrightness: 100, // chat panel brightness, independent of the game
};

function loadSettings() {
  let stored = {};
  try {
    // strip a UTF-8 BOM if present (e.g. from an external editor) so JSON.parse
    // doesn't choke and silently discard all settings
    stored = JSON.parse(fs.readFileSync(settingsPath(), "utf8").replace(/^﻿/, ""));
  } catch {
    /* first run */
  }
  // Migrate from the old grayscale-slider format
  if (typeof stored.grayscale === "number" && stored.tone === undefined) {
    stored.tone = stored.grayscale > 0 ? "gray" : "none";
    stored.toneAmount = stored.grayscale > 0 ? stored.grayscale : stored.lastGrayscale || 100;
  }
  delete stored.grayscale;
  delete stored.lastGrayscale;
  delete stored.browserBounds;
  settings = { ...settings, ...stored };
  if (!TONES.includes(settings.tone)) {
    settings.tone = "none";
  }
  if (!TONES.includes(settings.lastTone) || settings.lastTone === "none") {
    settings.lastTone = "gray";
  }
  settings.toneAmount = Math.min(Math.max(settings.toneAmount, 0), 100);
  settings.brightness = Math.min(Math.max(settings.brightness, BRIGHTNESS_MIN), 100);
  settings.opacity = Math.min(Math.max(settings.opacity || 100, OPACITY_MIN), 100);
  settings.muted = settings.muted !== false;
  settings.chatPanelWidth = Math.min(Math.max(settings.chatPanelWidth || 240, PANEL_W_MIN), PANEL_W_MAX);
  settings.panelBrightness = Math.min(Math.max(settings.panelBrightness || 100, BRIGHTNESS_MIN), 100);
}

function saveSettings() {
  try {
    // Don't clobber a key that was set on disk (e.g. edited externally) with an
    // empty in-memory one — preserve the disk key when we have none.
    const out = { ...settings };
    if (!out.claudeApiKey) {
      try {
        const disk = JSON.parse(fs.readFileSync(settingsPath(), "utf8"));
        if (disk.claudeApiKey) {
          out.claudeApiKey = disk.claudeApiKey;
          settings.claudeApiKey = disk.claudeApiKey;
        }
      } catch {
        /* no prior file */
      }
    }
    fs.writeFileSync(settingsPath(), JSON.stringify(out, null, 2));
  } catch {
    /* not fatal */
  }
}

let win = null;
let gameView = null;
let tray = null;
let hiddenByBossKey = false;
let windowFocused = true;

// ---- tabs ----
const webTabs = []; // { id, view }
let activeTabId = "game"; // "game" | number
let nextTabId = 1;

function normalizeUrl(input) {
  let target = String(input).trim();
  if (!/^[a-z]+:\/\//i.test(target)) {
    target =
      /\s/.test(target) || !target.includes(".")
        ? `https://www.google.com/search?q=${encodeURIComponent(target)}`
        : `https://${target}`;
  }
  return target;
}

function allViews() {
  return gameView ? [gameView, ...webTabs.map(t => t.view)] : webTabs.map(t => t.view);
}

function activeView() {
  if (activeTabId === "game") {
    return gameView;
  }
  const t = webTabs.find(t => t.id === activeTabId);
  return t ? t.view : gameView;
}

function panelSend(channel, payload) {
  if (win && !win.webContents.isDestroyed()) {
    win.webContents.send(channel, payload);
  }
}

function layoutViews() {
  if (!win) {
    return;
  }
  const [w, h] = win.getContentSize();
  const x = chatPanelOpen ? PICKUP_RAIL_W + settings.chatPanelWidth : 0;
  const b = { x, y: chromeHeight, width: Math.max(0, w - x), height: Math.max(0, h - chromeHeight) };
  for (const v of allViews()) {
    v.setBounds(b);
  }
}

function sendTabs() {
  panelSend("tabs", [
    { id: "game", title: "게임", active: activeTabId === "game" },
    ...webTabs.map(t => ({
      id: t.id,
      title: t.view.webContents.getTitle() || "새 탭",
      active: t.id === activeTabId,
    })),
  ]);
}

function sendUrl() {
  const t = webTabs.find(t => t.id === activeTabId);
  panelSend("url", t ? t.view.webContents.getURL() : "");
}

function focusActive() {
  const v = activeView();
  if (v) {
    v.webContents.focus();
  }
}

function activateTab(id) {
  if (id !== "game" && !webTabs.some(t => t.id === id)) {
    return;
  }
  activeTabId = id;
  gameView.setVisible(id === "game");
  for (const t of webTabs) {
    t.view.setVisible(t.id === id);
  }
  sendTabs();
  sendUrl();
  focusActive();
}

function newWebTab(url, focusAddress = false) {
  const view = new WebContentsView({
    webPreferences: {
      partition: "persist:pokerogue-browser",
      preload: path.join(__dirname, "web-preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  const id = nextTabId++;
  webTabs.push({ id, view });
  win.contentView.addChildView(view);
  view.setVisible(false);
  layoutViews();
  updateMute();

  const wc = view.webContents;
  wc.setWindowOpenHandler(({ url: u }) => {
    newWebTab(u);
    return { action: "deny" };
  });
  const refresh = () => {
    sendTabs();
    if (id === activeTabId) {
      sendUrl();
    }
  };
  wc.on("did-navigate", refresh);
  wc.on("did-navigate-in-page", refresh);
  wc.on("page-title-updated", sendTabs);
  attachHotkeys(wc);

  wc.loadURL(normalizeUrl(url || WEB_HOME_URL)).catch(() => {});
  activateTab(id);
  if (focusAddress) {
    panelSend("focus-address");
    win.webContents.focus();
  }
  return id;
}

function closeWebTab(id) {
  const idx = webTabs.findIndex(t => t.id === id);
  if (idx === -1) {
    return;
  }
  const [t] = webTabs.splice(idx, 1);
  win.contentView.removeChildView(t.view);
  t.view.webContents.close();
  if (activeTabId === id) {
    activateTab(webTabs.length > 0 ? webTabs[Math.min(idx, webTabs.length - 1)].id : "game");
  } else {
    sendTabs();
  }
}

function cycleTab(dir) {
  const order = ["game", ...webTabs.map(t => t.id)];
  if (order.length < 2) {
    return;
  }
  const idx = order.indexOf(activeTabId);
  activateTab(order[(idx + dir + order.length) % order.length]);
}

// ---- state / filters ----

function pushState() {
  panelSend("state", settings);
}

function updateMute() {
  const mute = settings.muted || !windowFocused || hiddenByBossKey;
  for (const v of allViews()) {
    v.webContents.setAudioMuted(mute);
  }
}

function applyFilters() {
  if (!gameView) {
    return;
  }
  const filters = [];
  if (settings.tone === "gray" && settings.toneAmount > 0) {
    filters.push(`grayscale(${settings.toneAmount / 100})`);
  } else if (settings.tone === "sepia" && settings.toneAmount > 0) {
    filters.push(`sepia(${settings.toneAmount / 100})`);
  }
  if (settings.brightness < 100) {
    filters.push(`brightness(${settings.brightness / 100})`);
  }
  const filter = filters.join(" ");
  gameView.webContents
    .executeJavaScript(`document.documentElement.style.filter = ${JSON.stringify(filter)}; undefined;`)
    .catch(() => {
      /* page not ready yet; dom-ready will re-apply */
    });
  const toneTag =
    settings.tone !== "none" && settings.toneAmount > 0
      ? ` [${settings.tone === "gray" ? "BW" : "SP"} ${settings.toneAmount}%]`
      : "";
  const tags = [
    toneTag,
    settings.brightness < 100 ? ` [${settings.brightness}%]` : "",
    settings.muted ? " [🔇]" : "",
    settings.alwaysOnTop ? " [TOP]" : "",
  ].join("");
  if (win) {
    win.setTitle(`PokeRogue Mini${tags}`);
  }
  pushState();
}

function updateSettings(patch) {
  Object.assign(settings, patch);
  settings.toneAmount = Math.min(Math.max(settings.toneAmount, 0), 100);
  settings.brightness = Math.min(Math.max(settings.brightness, BRIGHTNESS_MIN), 100);
  settings.opacity = Math.min(Math.max(settings.opacity, OPACITY_MIN), 100);
  settings.chatPanelWidth = Math.min(Math.max(settings.chatPanelWidth, PANEL_W_MIN), PANEL_W_MAX);
  settings.panelBrightness = Math.min(Math.max(settings.panelBrightness, BRIGHTNESS_MIN), 100);
  if (settings.tone !== "none") {
    settings.lastTone = settings.tone;
  }
  if ("chatPanelWidth" in patch) {
    layoutViews();
  }
  if ("alwaysOnTop" in patch && win) {
    win.setAlwaysOnTop(settings.alwaysOnTop);
  }
  if ("opacity" in patch && win) {
    win.setOpacity(settings.opacity / 100);
  }
  if ("muted" in patch) {
    updateMute();
  }
  saveSettings();
  applyFilters();
}

function togglePreset() {
  if (!win) {
    return;
  }
  const bounds = win.getBounds();
  const workArea = screen.getDisplayMatching(bounds).workArea;
  const isMini = bounds.width <= PRESET_MINI.width + 40;
  if (isMini) {
    win.setBounds({
      width: PRESET_NORMAL.width,
      height: PRESET_NORMAL.height,
      x: workArea.x + Math.round((workArea.width - PRESET_NORMAL.width) / 2),
      y: workArea.y + Math.round((workArea.height - PRESET_NORMAL.height) / 2),
    });
  } else {
    win.setBounds({
      width: PRESET_MINI.width,
      height: PRESET_MINI.height,
      x: workArea.x + workArea.width - PRESET_MINI.width - 12,
      y: workArea.y + workArea.height - PRESET_MINI.height - 12,
    });
  }
  settings.bounds = win.getBounds();
  saveSettings();
}

function toggleBossKey() {
  if (!win) {
    return;
  }
  if (win.isVisible() && !win.isMinimized()) {
    hiddenByBossKey = true;
    updateMute();
    win.hide();
  } else {
    hiddenByBossKey = false;
    win.show();
    win.focus();
    updateMute();
  }
}

function attachHotkeys(wc) {
  wc.on("before-input-event", (event, input) => {
    if (input.type !== "keyDown" || !input.control || input.alt || input.meta || input.isAutoRepeat) {
      return;
    }
    const key = input.key.toLowerCase();
    if (key === "g") {
      updateSettings({ tone: settings.tone !== "none" ? "none" : settings.lastTone });
    } else if (key === "m") {
      updateSettings({ muted: !settings.muted });
    } else if (key === "p") {
      togglePreset();
    } else if (key === "arrowdown") {
      updateSettings({ brightness: settings.brightness - STEP });
    } else if (key === "arrowup") {
      updateSettings({ brightness: settings.brightness + STEP });
    } else if (key === "arrowleft") {
      updateSettings({ opacity: settings.opacity - STEP });
    } else if (key === "arrowright") {
      updateSettings({ opacity: settings.opacity + STEP });
    } else if (key === "r") {
      activeView()?.webContents.reload();
    } else if (key === "t" && !input.shift) {
      newWebTab();
    } else if (key === "w") {
      if (activeTabId !== "game") {
        closeWebTab(activeTabId);
      }
    } else if (key === "tab") {
      cycleTab(input.shift ? -1 : 1);
    } else if (key === "l") {
      if (activeTabId === "game") {
        newWebTab(WEB_HOME_URL, true);
      } else {
        panelSend("focus-address");
        win.webContents.focus();
      }
    } else if (key === "t" && input.shift) {
      updateSettings({ alwaysOnTop: !settings.alwaysOnTop });
    } else {
      return;
    }
    event.preventDefault();
  });
}

function createWindow() {
  const ses = session.fromPartition("persist:pokerogue");
  ses.setUserAgent(CHROME_UA);
  session.fromPartition("persist:pokerogue-browser").setUserAgent(CHROME_UA);

  win = new BrowserWindow({
    width: settings.bounds.width,
    height: settings.bounds.height,
    x: settings.bounds.x,
    y: settings.bounds.y,
    backgroundColor: "#141416",
    alwaysOnTop: settings.alwaysOnTop,
    title: "PokeRogue Mini",
    // no native caption text; the toolbar doubles as the (dark) title bar
    titleBarStyle: "hidden",
    titleBarOverlay: { color: "#141416", symbolColor: "#7c7c82", height: 30 },
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  win.setMenu(null);
  if (settings.opacity < 100) {
    win.setOpacity(settings.opacity / 100);
  }
  win.loadFile("toolbar.html");
  win.webContents.on("dom-ready", () => {
    pushState();
    sendTabs();
  });

  gameView = new WebContentsView({
    webPreferences: {
      partition: "persist:pokerogue",
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  win.contentView.addChildView(gameView);
  layoutViews();
  win.on("resize", layoutViews);

  // Open external links (oauth popups etc.) in the default browser.
  gameView.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: "deny" };
  });

  // The inline style is per-document; re-apply after every navigation.
  gameView.webContents.on("dom-ready", applyFilters);

  attachHotkeys(gameView.webContents);
  attachHotkeys(win.webContents);

  // Auto-mute while the window is not focused.
  win.on("blur", () => {
    windowFocused = false;
    updateMute();
  });
  win.on("focus", () => {
    windowFocused = true;
    updateMute();
    // keyboard input should go to the active tab by default
    focusActive();
  });

  const rememberBounds = () => {
    if (win && !win.isMinimized() && win.isVisible()) {
      settings.bounds = win.getBounds();
    }
  };
  win.on("resized", rememberBounds);
  win.on("moved", rememberBounds);
  win.on("close", () => {
    rememberBounds();
    saveSettings();
  });

  updateMute();
  gameView.webContents.loadURL(HOME_URL);
}

function createTray() {
  tray = new Tray(nativeImage.createFromDataURL(TRAY_ICON));
  tray.setToolTip("PokeRogue Mini — 클릭: 보이기/숨기기");
  tray.on("click", toggleBossKey);
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: "보이기/숨기기 (Ctrl+Alt+P)", click: toggleBossKey },
      { type: "separator" },
      { label: "종료", click: () => app.quit() },
    ]),
  );
}

// Isolated profile for development/testing so a running instance isn't disturbed.
if (process.argv.includes("--test-profile")) {
  app.setPath("userData", path.join(app.getPath("temp"), "pokerogue-mini-test-profile"));
}

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  console.error("another instance is already running; exiting");
  app.quit();
} else {
  process.on("uncaughtException", err => {
    console.error("uncaught exception:", err);
  });

  app.on("second-instance", () => {
    if (win) {
      if (hiddenByBossKey) {
        toggleBossKey();
      }
      if (win.isMinimized()) {
        win.restore();
      }
      win.focus();
    }
  });

  ipcMain.on("set", (_e, patch) => updateSettings(patch));
  ipcMain.on("reload", () => activeView()?.webContents.reload());
  ipcMain.on("boss", toggleBossKey);
  ipcMain.on("preset", togglePreset);
  ipcMain.on("focus-game", focusActive);
  ipcMain.on("chat-toggle", (_e, isOpen) => {
    chatPanelOpen = Boolean(isOpen);
    layoutViews();
  });
  // live (unsaved) panel width while the user drags the resizer
  ipcMain.on("panel-width", (_e, w) => {
    if (typeof w === "number") {
      settings.chatPanelWidth = Math.min(Math.max(Math.round(w), PANEL_W_MIN), PANEL_W_MAX);
      layoutViews();
    }
  });
  ipcMain.handle("pickup-week", () => pickup.getUpcoming(7));
  ipcMain.on("tab-new", () => newWebTab());
  ipcMain.on("tab-close", (_e, id) => closeWebTab(id));
  ipcMain.on("tab-activate", (_e, id) => activateTab(id));
  ipcMain.on("nav", (_e, dir) => {
    const v = activeTabId === "game" ? null : activeView();
    if (!v) {
      return;
    }
    const nav = v.webContents.navigationHistory;
    if (dir === "back" && nav.canGoBack()) {
      nav.goBack();
    } else if (dir === "forward" && nav.canGoForward()) {
      nav.goForward();
    }
  });
  ipcMain.on("navigate", (_e, url) => {
    if (typeof url !== "string" || !url.trim()) {
      return;
    }
    if (activeTabId === "game") {
      newWebTab(url);
    } else {
      activeView().webContents.loadURL(normalizeUrl(url)).catch(() => {});
    }
  });
  ipcMain.on("chrome-height", (_e, h) => {
    const clamped = Math.min(Math.max(Math.round(h), 20), 160);
    if (clamped !== chromeHeight) {
      chromeHeight = clamped;
      layoutViews();
    }
  });

  app.whenReady().then(() => {
    loadSettings();
    chat.init({ settings, save: saveSettings, target: () => (win ? win.webContents : null) });
    createWindow();
    createTray();
    globalShortcut.register("Control+Alt+P", toggleBossKey);
  });

  app.on("will-quit", () => {
    globalShortcut.unregisterAll();
  });

  app.on("window-all-closed", () => {
    app.quit();
  });
}
